# Generated by Django 5.0.6 on 2024-07-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotework_app', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='some_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='some_password', max_length=128),
        ),
    ]
