# Generated by Django 5.0.6 on 2024-07-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotework_app', '0003_user_is_superuser_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
