# Generated by Django 5.0.6 on 2024-08-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotework_app', '0004_remove_user_is_superuser_remove_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Discription', models.CharField(max_length=255)),
                ('AssignedTo', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('priority', models.IntegerField(max_length=255)),
                ('Due_date', models.DateField(max_length=255)),
                ('Created_at', models.DateField(max_length=10)),
                ('Updated_at', models.DateField(max_length=10)),
            ],
        ),
    ]
