# Generated by Django 5.0.6 on 2024-08-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotework_app', '0005_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
